name: Matlab Package

on:
  workflow_dispatch:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  release:
    types: ['released', 'prereleased']

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            name: glnxa64
            matlab-release: 'R2021a'
            host: x86_64-bionic-linux-gnu
          - os: macos-14
            name: maca64
            matlab-release: 'R2023b'
            host: macos
          - os: macos-13
            name: maci64
            matlab-release: 'R2021a'
            host: macos
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Conan and sccache
      uses: ./.github/workflows/setup-conan
      with:
        python-version: '3.12'
        cache-key: build-matlab-${{ matrix.name }}

    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@64144ac4bb7c754f9ef7642f693671c873701c60
      id: matlab
      with:
        release: ${{ matrix.matlab-release }}

    - name: Build
      run: >
        bash scripts/ci/build-matlab.sh
        "${{ steps.matlab.outputs.matlabroot }}" ${{ matrix.host }} . staging

    - name: Package
      run: zip -r ../qpalm-matlab-${{ matrix.name }}.zip ./*
      working-directory: staging

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: qpalm-matlab-${{ matrix.name }}
        path: qpalm-matlab-${{ matrix.name }}.zip
    - name: Release
      if: ${{ github.event.action == 'released' || github.event.action == 'prereleased' }}
      uses: softprops/action-gh-release@17cd0d34deddf848fc0e7d9be5202c148c270a0a
      with:
        files: qpalm-matlab-${{ matrix.name }}.zip

    - run: conan cache clean

  build-windows:
    strategy:
      matrix:
        include:
          - os: windows-2022
            name: win64
            matlab-release: 'R2021a'
            host: amd64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Conan and sccache
      uses: ./.github/workflows/setup-conan
      with:
        python-version: '3.12'
        cache-key: build-matlab-${{ matrix.name }}

    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@64144ac4bb7c754f9ef7642f693671c873701c60
      id: matlab
      with:
        release: ${{ matrix.matlab-release }}

    - name: Build
      shell: cmd
      run: >
        call .\scripts\ci\build-matlab-windows.bat
        "${{ steps.matlab.outputs.matlabroot }}" "${{ matrix.host }}" "." "staging"

    - name: Package
      shell: pwsh
      run: Compress-Archive -Path staging\* qpalm-matlab-${{ matrix.name }}.zip

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: qpalm-matlab-${{ matrix.name }}
        path: qpalm-matlab-${{ matrix.name }}.zip
    - name: Release
      if: ${{ github.event.action == 'released' || github.event.action == 'prereleased' }}
      uses: softprops/action-gh-release@17cd0d34deddf848fc0e7d9be5202c148c270a0a
      with:
        files: qpalm-matlab-${{ matrix.name }}.zip

    - run: conan cache clean
